data:
  root: "./data"
  download: true

hyperparameters:
  hidden_dim: 256
  latent_dim: 32
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 50

folds:
  num_folds: 10

training:
  seed: 42
  num_workers: 0
classifier:
  hidden_dim: 392
  train_epochs: 50
paths:
  model_dir: "./models"
  final_model_name: "latent2.eqx"
  classifier_name: "classifier"

visualization:
  num_examples: 5 
