data:
  root: "./data"
  download: true

hyperparameters:
  hidden_dim: 256
  latent_dim: 32
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 50

folds:
  num_folds: 10

training:
  seed: 42
  num_workers: 0
classifier:
  hidden_dim: 392
  train_epochs: 10
paths:
  model_dir: "./models"
<<<<<<< HEAD
  final_model_name: "latent2.eqx"
  classifier_name: "classifier"
=======
  final_model_name: "cifarmodel.eqx"
>>>>>>> 75181ed1b638dbcdb23dca2263c4024ee5e442e2

visualization:
  num_examples: 5 
